import { Message, ReplyTemplate } from "./types";

// Helper to generate timestamps relative to now
function hoursAgo(h: number) {
  return new Date(Date.now() - h * 3600000).toISOString();
}

export const mockMessages: Message[] = [
  {
    id: "1",
    sender: "Nike Brand Team",
    platform: "instagram",
    content: "Hey! We'd love to discuss a partnership for our spring campaign. We're looking for creators with authentic audiences in the fitness/lifestyle space. Would you be open to a call this week? Budget is $8-12k for a 3-post series.",
    preview: "Hey! We'd love to discuss a partnership for our spring campaign...",
    timestamp: hoursAgo(0.03),
    tag: "collab",
    confidence: 96,
    read: false,
    archived: false,
  },
  {
    id: "2",
    sender: "Sarah M.",
    platform: "tiktok",
    content: "OMG I love your latest video! The editing was incredible 🔥 How do you get that transition effect? I've been trying to replicate it for weeks!",
    preview: "OMG I love your latest video! The editing was incredible 🔥",
    timestamp: hoursAgo(0.5),
    tag: "fan",
    confidence: 89,
    read: false,
    archived: false,
  },
  {
    id: "3",
    sender: "TechStartup CEO",
    platform: "gmail",
    content: "Hi, we have a $5k budget for a sponsored review of our new productivity app. We've seen your tech content and think you'd be a great fit. The app launches March 15th. Interested?",
    preview: "Hi, we have a $5k budget for a sponsored review of our new app...",
    timestamp: hoursAgo(1.5),
    tag: "collab",
    confidence: 94,
    read: false,
    archived: false,
  },
  {
    id: "4",
    sender: "Unknown",
    platform: "instagram",
    content: "🎉 Congratulations! You've been selected for a FREE iPhone 16 Pro Max! Click here to claim your prize NOW! Limited time offer!!!",
    preview: "🎉 Congratulations! You've been selected for a FREE iPhone...",
    timestamp: hoursAgo(3),
    tag: "spam",
    confidence: 99,
    read: true,
    archived: false,
  },
  {
    id: "5",
    sender: "Adidas Originals",
    platform: "twitter",
    content: "We're reaching out to select creators for our upcoming Originals campaign. This would involve a 2-week content series featuring our new retro collection. Compensation starts at $15k. Let us know if you're interested!",
    preview: "We're reaching out to select creators for our upcoming Originals...",
    timestamp: hoursAgo(5),
    tag: "collab",
    confidence: 97,
    read: true,
    archived: false,
  },
  {
    id: "6",
    sender: "Jake R.",
    platform: "tiktok",
    content: "Your content literally inspired me to start my own channel. Just hit 1k followers! Thank you so much for being such a positive influence 💪",
    preview: "Your content literally inspired me to start my own channel...",
    timestamp: hoursAgo(8),
    tag: "fan",
    confidence: 92,
    read: true,
    archived: false,
  },
  {
    id: "7",
    sender: "CryptoGains2026",
    platform: "twitter",
    content: "I made $50,000 in just 2 days using this secret trading bot! DM me for access. Only 10 spots left! 🚀💰",
    preview: "I made $50,000 in just 2 days using this secret trading bot...",
    timestamp: hoursAgo(20),
    tag: "spam",
    confidence: 98,
    read: true,
    archived: false,
  },
  {
    id: "8",
    sender: "Maria L.",
    platform: "instagram",
    content: "Hey! I run a small beauty brand and would love to send you some products to try. No obligations, just thought you might like them based on your skincare routine posts. Let me know your address!",
    preview: "Hey! I run a small beauty brand and would love to send you...",
    timestamp: hoursAgo(26),
    tag: "collab",
    confidence: 78,
    read: false,
    archived: false,
  },
  {
    id: "9",
    sender: "Alex P.",
    platform: "facebook",
    content: "Hey, just wanted to say I shared your post with my whole friend group. Everyone loved it! Keep creating amazing stuff 🙌",
    preview: "Hey, just wanted to say I shared your post with my whole...",
    timestamp: hoursAgo(30),
    tag: "fan",
    confidence: 85,
    read: true,
    archived: false,
  },
  {
    id: "10",
    sender: "PodcastHost",
    platform: "gmail",
    content: "Would you be interested in being a guest on our podcast? We have 50k weekly listeners in the creator economy space. The episode would go live in March. Happy to work around your schedule.",
    preview: "Would you be interested in being a guest on our podcast?...",
    timestamp: hoursAgo(36),
    tag: "other",
    confidence: 72,
    read: false,
    archived: false,
  },
  {
    id: "11",
    sender: "Emma W.",
    platform: "instagram",
    content: "Can you do a tutorial on how you edit your reels? The color grading is so unique! I'd totally watch a full breakdown 🎨",
    preview: "Can you do a tutorial on how you edit your reels?...",
    timestamp: hoursAgo(40),
    tag: "fan",
    confidence: 87,
    read: true,
    archived: false,
  },
  {
    id: "12",
    sender: "FreeFollowers.io",
    platform: "instagram",
    content: "Get 10,000 REAL followers in 24 hours! Visit our website now for a free trial. 100% safe and guaranteed results!!! 📈",
    preview: "Get 10,000 REAL followers in 24 hours! Visit our website...",
    timestamp: hoursAgo(48),
    tag: "spam",
    confidence: 99,
    read: true,
    archived: true,
  },
];

export const mockTemplates: ReplyTemplate[] = [
  {
    id: "t1",
    name: "Collab Interest",
    content: "Thanks for reaching out! I'd love to learn more about this opportunity. Could you share more details about the timeline, deliverables, and compensation? Looking forward to hearing from you!",
    tag: "collab",
  },
  {
    id: "t2",
    name: "Polite Decline",
    content: "Thank you so much for thinking of me! Unfortunately, I'm not able to take on new collaborations at this time. I'll keep you in mind for future opportunities though!",
    tag: "collab",
  },
  {
    id: "t3",
    name: "Fan Thank You",
    content: "Thank you so much for the kind words! Messages like yours really make my day and motivate me to keep creating. I appreciate you! 💙",
    tag: "fan",
  },
  {
    id: "t4",
    name: "Rate Card Request",
    content: "Thanks for your interest! I'd be happy to share my rate card and media kit. What platforms and deliverable types are you looking at? I'll put together a custom proposal for you.",
    tag: "collab",
  },
];
